const APPS=[{file:'sausage-journal.html',name:'Sausage Journal',blurb:'Digital calm journal',price:'$19 pack',id:'journal'},{file:'wiener-wisdom.html',name:'Wiener Wisdom',blurb:'Daily dachshund cards',price:'$9 / month',id:'wisdom'},{file:'calm-coaster.html',name:'Calm Coaster',blurb:'Mobile therapy leads',price:'$180 booking',id:'coaster'},{file:'sound-den.html',name:'Sound Den',blurb:'Ambient audio + tips',price:'$7 tip',id:'sound'},{file:'peace-pledge.html',name:'Peace Pledge',blurb:'Micro-giving notes',price:'$3 pledge',id:'pledge'},{file:'farm-stay.html',name:'Farm Stay Whisper',blurb:'Forevermore waitlist',price:'$49 hold',id:'farm'},{file:'therapy-faq.html',name:'Therapy FAQ Desk',blurb:'Lead magnet + consults',price:'$220 consult',id:'faq'},{file:'grant-spark.html',name:'Grant Spark',blurb:'Grant idea generator',price:'Lead to pack',id:'grant'},{file:'breath-balance.html',name:'Breath Balance',blurb:'Two-minute peace timer',price:'$5 / week',id:'breath'},{file:'human-campaigns.html',name:'Human Campaigns',blurb:'Paid ads with human feel',price:'Campaigns',id:'ads'}];
const KEY='lifeMakerV1';
function load(){try{return JSON.parse(localStorage.getItem(KEY)||'{}')}catch(e){return {}}}
function save(d){localStorage.setItem(KEY,JSON.stringify(d))}
function seed(){const d=load();if(!d.seeded){d.seeded=true;d.pool=18640;d.give=10;d.apps={};const demo=[2200,980,5400,410,260,1900,1760,0,730,5000];APPS.forEach((a,i)=>d.apps[a.id]=demo[i]);d.tx=[{t:Date.now()-86400000,app:'coaster',amount:180,note:'Corporate calm visit'},{t:Date.now()-3600000,app:'journal',amount:19,note:'Journal pack'}];save(d);}}
function money(n){return '$'+Number(n||0).toLocaleString('en-AU')}
function render(){const d=load();document.getElementById('pool').textContent=money(d.pool||0);document.getElementById('bar').style.width=Math.min(100,(d.pool||0)/400)+'%';document.getElementById('give').textContent=(d.give||10)+'% reserved for peace, dogs, quiet earth ≈ '+money(((d.pool||0)*(d.give||10))/100);document.getElementById('apps').innerHTML=APPS.map(a=>'<a class="card" href="apps/'+a.file+'"><div class="k">'+a.price+'</div><h3>'+a.name+'</h3><p class="lede">'+a.blurb+'</p><div class="num">'+money((d.apps||{})[a.id]||0)+'</div></a>').join('');document.getElementById('led').innerHTML=(d.tx||[]).slice(0,12).map(x=>'<tr><td>'+new Date(x.t).toLocaleString()+'</td><td>'+x.app+'</td><td>'+(x.note||'')+'</td><td>'+money(x.amount)+'</td></tr>').join('')||'<tr><td colspan=4>No movements yet</td></tr>';}
function setGive(v){const d=load();d.give=+v;save(d);render();}
function opt(m){const r=document.documentElement.style;if(m==='warm'){r.setProperty('--bg','#1a1410');r.setProperty('--gold','#f0c48a');}if(m==='clear'){r.setProperty('--bg','#0b1220');r.setProperty('--gold','#e8c36a');}if(m==='gold'){r.setProperty('--bg','#140f08');r.setProperty('--gold','#ffd98a');}}
function feel(){const w=+warmth.value,c=+clarity.value,u=+urgency.value;feelLine.textContent='Copy tone: '+(w>60?'tender':'crisp')+', '+(c>50?'specific':'poetic')+'. Urgency '+(u<35?'kept low so humans stay human.':'raised for launch bursts only.');}
seed();render();feel();
